# Hotkey to open chat
hotkey: MpTextChatAll # T

# Message prefix to be considered a command
# Set to blank string to treat all messages as commands
command_prefix: /

# Number of historical messages a client stores
history_limit: 50

# Message template for non command messages
default_template: <h1><i class="fas fa-fw fa-star"></i> {0}</h1>{1}

# Message style for non command messages
# Styles: Primary|Secondary|Success|Danger|Warning|Info|Light|Dark
default_style: Secondary
